### ISSUE TITLE
Inappropriate use of the arduino-library topic

### ISSUE THREAD

**Issue by per1234** [Crista2019/Independent-Study-2015-2016#1]
This repository is not an Arduino library, thus the use of the `arduino-library` topic is inappropriate.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the X to the right of `arduino-library`.

**Comment by Crista2019** [comment]
Although "arduino-library" is not included among the topics for this repository, I will take your comment into consideration when revising related topics. Thank you.

**Comment by per1234** [comment]
>"arduino-library" is not included among the topics for this repository

It's right here:
![clipboard01](https://user-images.githubusercontent.com/8572152/41765871-34e1f6a6-75ba-11e8-9866-062267f54522.png)

**Comment by Crista2019** [comment]
Haha, gotcha. I had to view the repository from a different device due to screen size. Absolutely my mistake. Thank you, and the issue is resolved.
